import{S as b,a as L,i as l}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(r){if(r.ep)return;r.ep=!0;const t=s(r);fetch(r.href,t)}})();let c;function d(e){const o=document.querySelector("#gallery");o.innerHTML=e.map(({webformatURL:s,largeImageURL:a,tags:r,likes:t,views:i,comments:g,downloads:p})=>`
    <a class="gallery-link" href="${a}">
    <img src="${s}" class="gallery-image" alt="${r}" loading="lazy"/>
        <div class="inform">
            <p><b>Likes</b>: ${t}</p>
            <p><b>Views</b>: ${i}</p>
            <p><b>Comments</b>: ${g}</p>
            <p><b>Downloads</b>: ${p}</p>
        </div>
    </a>
    `).join(""),c?c.refresh():c=new b(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function q(){const e=document.querySelector("#gallery");e.innerHTML=""}const S="is-hidden";function $(e){e.classList.add(S)}const v="44717269-26bd411e987b6b0139d6ec9c5";async function y(e,o=1){const s=`https://pixabay.com/api/?key=${v}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=15`;try{return(await L.get(s)).data}catch{l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}}let n=1,f="";const m=document.querySelector(".form"),w=document.querySelector(".gallery"),u=document.querySelector(".loader"),P=document.querySelector(".load-more");m.addEventListener("submit",E);async function E(e){e.preventDefault(),w.innerHTML="";const o=e.currentTarget.elements.query.value.trim();if(!o){l.error({title:"Error",message:"❌ Please enter a search query"});return}u.classList.remove("hidden"),f=o,n=1,q();try{const s=await y(o,n);s.hits.length===0?l.warning({title:"No Results",message:"Sorry, there are no images matching your search query."}):(d(s.hits),s.totalHits>n*15)}catch{h()}finally{u.classList.add("hidden"),m.reset()}}function h(e){l.error({title:"Error",message:"❌ No pictures found"})}P.addEventListener("click",H);async function H(){n+=1,$(hiddenClass);try{const e=await y(f,n);d(e.hits),n*15>=e.totalHits&&l.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),M()}catch{h()}finally{}}function M(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
